"""
evidence_export.py
===================
Turns a Case into an exportable evidence package:

 - <case_id>.json         structured machine-readable case data
 - <case_id>_report.txt   human-readable evidence report
 - <case_id>_report.pdf   (only if reportlab is installed)
 - <case_id>_package.zip  the above + any original uploaded files

AI-generated conclusions are always clearly labeled as analysis, not
verified fact, per ScamHunt's evidence-integrity requirements.
"""

import json
import os
import zipfile

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas
    from reportlab.lib.utils import simpleSplit
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False


def build_text_report(case):
    lines = []
    lines.append("=" * 70)
    lines.append("SCAMHUNT — EVIDENCE / INCIDENT REPORT")
    lines.append("=" * 70)
    lines.append(f"Case ID:        {case.case_id}")
    lines.append(f"Created:        {case.created_at}")
    lines.append(f"Last updated:   {case.updated_at}")
    lines.append(f"Status:         {case.status}")
    lines.append(f"Risk level:     {case.risk_level}  (score {case.risk_score}/100)")
    lines.append(f"Likely category:{' ' + case.category}")
    lines.append("")
    lines.append("NOTE: Risk level, category, and indicators below are produced by")
    lines.append("ScamHunt's automated heuristic analysis engine. They are ANALYSIS,")
    lines.append("not a verified legal or forensic determination.")
    lines.append("")
    if case.description:
        lines.append("-" * 70)
        lines.append("INCIDENT DESCRIPTION (user-provided)")
        lines.append("-" * 70)
        lines.append(case.description)
        lines.append("")

    lines.append("-" * 70)
    lines.append(f"EVIDENCE ITEMS ({len(case.evidence)})")
    lines.append("-" * 70)
    for ev in case.evidence:
        lines.append(f"[{ev['evidence_id']}] Type: {ev['type']}  Added: {ev['created_at']}")
        if ev.get("original_filename"):
            lines.append(f"    Original filename: {ev['original_filename']}")
        if ev.get("sha256"):
            lines.append(f"    SHA-256: {ev['sha256']}")
        data = ev.get("data")
        if isinstance(data, str) and ev["type"] in ("url", "text", "qr", "payment_qr"):
            snippet = data if len(data) < 500 else data[:500] + " …[truncated]"
            lines.append(f"    Content: {snippet}")
        lines.append("")

    lines.append("-" * 70)
    lines.append("AI ANALYSIS LOG")
    lines.append("-" * 70)
    for entry in case.analysis_log:
        a = entry["analysis"]
        lines.append(f"[{entry['evidence_id']}] ({entry['type']}) — Risk: {a.get('level','?')} (score {a.get('score','?')}/100)")
        cats = a.get("categories") or []
        if cats:
            lines.append(f"    Categories: {', '.join(cats)}")
        inds = a.get("indicators") or []
        if inds:
            lines.append(f"    Indicators: {', '.join(inds)}")
        reasons = a.get("reasons") or []
        for r in reasons:
            lines.append(f"    - {r}")
        if a.get("action"):
            lines.append(f"    Recommended action: {a['action']}")
        lines.append("")

    lines.append("-" * 70)
    lines.append("CASE TIMELINE")
    lines.append("-" * 70)
    for t in case.timeline:
        lines.append(f"{t['ts']}  —  {t['event']}")
    lines.append("")

    lines.append("-" * 70)
    lines.append("REPORTING GUIDANCE (India)")
    lines.append("-" * 70)
    lines.append("National Cyber Crime Reporting Portal: https://cybercrime.gov.in")
    lines.append("Cyber Crime Helpline: 1930")
    lines.append("If money was transferred, also contact your bank's fraud/helpline immediately.")
    lines.append("")
    lines.append("=" * 70)
    lines.append("END OF REPORT — Generated by ScamHunt (local heuristic analysis engine)")
    lines.append("=" * 70)
    return "\n".join(lines)


def build_pdf_report(case, out_path):
    if not PDF_AVAILABLE:
        return None
    text = build_text_report(case)
    c = canvas.Canvas(out_path, pagesize=A4)
    width, height = A4
    margin = 18 * mm
    y = height - margin
    font_size = 8.5
    c.setFont("Courier", font_size)
    line_height = font_size + 2

    for raw_line in text.split("\n"):
        wrapped = simpleSplit(raw_line, "Courier", font_size, width - 2 * margin) or [""]
        for line in wrapped:
            if y < margin:
                c.showPage()
                c.setFont("Courier", font_size)
                y = height - margin
            c.drawString(margin, y, line)
            y -= line_height
    c.save()
    return out_path


def export_case(case, out_dir, include_originals=True):
    """
    Writes json + txt (+ pdf if available) into out_dir, then zips
    everything (including original evidence files if include_originals
    and they still exist on disk) into a single package.

    Returns dict of produced file paths.
    """
    os.makedirs(out_dir, exist_ok=True)
    base = case.case_id

    json_path = os.path.join(out_dir, f"{base}.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(case.to_dict(), f, indent=2, ensure_ascii=False)

    txt_path = os.path.join(out_dir, f"{base}_report.txt")
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(build_text_report(case))

    pdf_path = os.path.join(out_dir, f"{base}_report.pdf")
    produced_pdf = build_pdf_report(case, pdf_path) if PDF_AVAILABLE else None

    zip_path = os.path.join(out_dir, f"{base}_package.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(json_path, arcname=os.path.basename(json_path))
        z.write(txt_path, arcname=os.path.basename(txt_path))
        if produced_pdf:
            z.write(pdf_path, arcname=os.path.basename(pdf_path))
        if include_originals:
            for ev in case.evidence:
                data = ev.get("data")
                if ev["type"] in ("image", "file") and isinstance(data, str) and os.path.exists(data):
                    arc = f"evidence/{ev['evidence_id']}_{ev.get('original_filename') or os.path.basename(data)}"
                    z.write(data, arcname=arc)

    return {
        "json": json_path,
        "txt": txt_path,
        "pdf": produced_pdf,
        "zip": zip_path,
    }
